export const placeholder = [
   {
      _id: '648b7add0905a510f1c7fdf8',
      title: 'Software Engineer',
      companyName: 'ABC Inc',
      city: 'New York',
      country: 'USA',
      workLocation: 'Remote',
      jobType: 'Full-time',
      seniority: 'Senior',
      salaryFrom: 100000,
      salaryTo: 150000,
      currency: 'USD',
      technologies: ['Java', 'Spring', 'React'],
      description:
         'We are hiring a Senior Software Engineer to join our team. You will be involved in developing and maintaining scalable software solutions using Java, Spring, and React. The ideal candidate should have strong programming skills and a solid understanding of software engineering principles.',
      offerUrl: 'https://nerdbord.io',
      __v: 0,
      createdAt: '2023-06-15T20:55:57.194Z',
      updatedAt: '2023-10-14T19:49:23.511Z',
      image: 'https://i.imgur.com/yaKYWeN.png',
   },
   {
      _id: '648b7add0905a510f1c7fdf9',
      title: 'Marketing Manager',
      companyName: 'XYZ Corp',
      city: 'London',
      country: 'UK',
      workLocation: 'Part-remote',
      jobType: 'Contract',
      seniority: 'Expert',
      salaryFrom: 80000,
      salaryTo: 120000,
      currency: 'GBP',
      technologies: ['Digital Marketing', 'SEO', 'Social Media'],
      description:
         'We are seeking an experienced Marketing Manager to lead our marketing initiatives. You will be responsible for developing and executing marketing strategies, optimizing SEO, and managing social media campaigns. The ideal candidate should have a proven track record in marketing and be knowledgeable about the latest digital marketing trends.',
      offerUrl: 'https://nerdbord.io',
      __v: 0,
      createdAt: '2023-06-15T20:55:57.197Z',
      updatedAt: '2023-10-14T19:49:23.556Z',
      image: 'https://i.imgur.com/yaKYWeN.png',
   },
   {
      _id: '648b7add0905a510f1c7fdfa',
      title: 'Front-end Developer',
      companyName: 'PQR Ltd',
      city: 'Sydney',
      country: 'Australia',
      workLocation: 'On-site',
      jobType: 'Part-time',
      seniority: 'Mid/Regular',
      salaryFrom: 40000,
      salaryTo: 60000,
      currency: 'AUD',
      technologies: ['HTML', 'CSS', 'JavaScript'],
      description:
         'We are looking for a skilled Front-end Developer to join our team on a part-time basis. You will be responsible for creating user-friendly web interfaces using HTML, CSS, and JavaScript. The ideal candidate should have a strong command of front-end technologies and be experienced in responsive design.',
      offerUrl: 'https://nerdbord.io',
      __v: 0,
      createdAt: '2023-06-15T20:55:57.197Z',
      updatedAt: '2023-10-14T19:49:23.609Z',
      image: 'https://i.imgur.com/uiDZrVV.png',
   },
   {
      _id: '648b7add0905a510f1c7fdfb',
      title: 'Data Analyst',
      companyName: 'LMN Co',
      city: 'Toronto',
      country: 'Canada',
      workLocation: 'Remote',
      jobType: 'Full-time',
      seniority: 'Junior',
      salaryFrom: 50000,
      salaryTo: 70000,
      currency: 'CAD',
      technologies: ['SQL', 'Python', 'Data Visualization'],
      description:
         'We are seeking a Data Analyst to join our team. You will be responsible for collecting, analyzing, and interpreting large datasets using SQL and Python. The ideal candidate should have strong problem-solving skills and be proficient in data visualization tools.',
      offerUrl: 'https://nerdbord.io',
      __v: 0,
      createdAt: '2023-06-15T20:55:57.197Z',
      updatedAt: '2023-10-14T19:49:23.657Z',
      image: 'https://i.imgur.com/eUxCdeB.png',
   },
   {
      _id: '648b7add0905a510f1c7fdfc',
      title: 'Graphic Designer',
      companyName: 'QRS GmbH',
      city: 'Berlin',
      country: 'Germany',
      workLocation: 'On-site',
      jobType: 'Full-time',
      seniority: 'Mid/Regular',
      salaryFrom: 40000,
      salaryTo: 60000,
      currency: 'EUR',
      technologies: ['Adobe Creative Suite', 'Illustrator', 'Photoshop'],
      description:
         'We are looking for a creative Graphic Designer to join our team. You will be responsible for designing visually appealing graphics using Adobe Creative Suite, Illustrator, and Photoshop. The ideal candidate should have a strong portfolio demonstrating their design skills and be familiar with current design trends.',
      offerUrl: 'https://nerdbord.io',
      __v: 0,
      createdAt: '2023-06-15T20:55:57.197Z',
      updatedAt: '2023-10-14T19:49:23.701Z',
      image: 'https://i.imgur.com/yaKYWeN.png',
   },
];
