import type { Metadata } from 'next';
import { poppins } from '@/ui/fonts';
import './globals.css';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${poppins.className} block min-h-screen bg-white bg-gradient-to-b text-gray-darkest antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
